# Generated by Django 2.2.3 on 2019-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20191120_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('od', 'organization_director'), ('oe', 'organization_employee'), ('em', 'employee')], max_length=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='organization',
            field=models.CharField(max_length=200),
        ),
    ]
