# Generated by Django 2.2.3 on 2019-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20191121_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestemtood',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('c', 'confirmed'), ('f', 'failed')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestemtooe',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('c', 'confirmed'), ('f', 'failed')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestoetood',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('c', 'confirmed'), ('f', 'failed')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
